# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'minichat.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(853, 746)
        MainWindow.setStyleSheet("QFrame {\n"
"    boder-color:  rgb(203, 203, 203);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_container = QtWidgets.QFrame(self.centralwidget)
        self.frame_container.setStyleSheet("QFrame {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_container.setObjectName("frame_container")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_container)
        self.verticalLayout.setObjectName("verticalLayout")
        self.output = QtWidgets.QFrame(self.frame_container)
        self.output.setStyleSheet("QFrame {\n"
"    border: 2px solid rgb(222, 222, 222);\n"
"}")
        self.output.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.output.setFrameShadow(QtWidgets.QFrame.Raised)
        self.output.setObjectName("output")
        self.scrollArea = QtWidgets.QScrollArea(self.output)
        self.scrollArea.setGeometry(QtCore.QRect(-1, -4, 581, 1000))
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 1000))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 560, 2000))
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(0, 2000))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.chat = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.chat.setGeometry(QtCore.QRect(0, 0, 561, 2000))
        self.chat.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.chat.setWordWrap(True)
        self.chat.setObjectName("chat")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.output)
        self.input = QtWidgets.QFrame(self.frame_container)
        self.input.setMaximumSize(QtCore.QSize(16777215, 150))
        self.input.setStyleSheet("QFrame {\n"
"    border: 2px solid rgb(222, 222, 222);\n"
"}")
        self.input.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input.setObjectName("input")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.input)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.input)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 491, 121))
        self.lineEdit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.input)
        self.frame_2.setMaximumSize(QtCore.QSize(55, 200))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.post = QtWidgets.QPushButton(self.frame_2)
        self.post.setMaximumSize(QtCore.QSize(55, 100))
        self.post.setObjectName("post")
        self.verticalLayout_2.addWidget(self.post)
        self.clear = QtWidgets.QPushButton(self.frame_2)
        self.clear.setMaximumSize(QtCore.QSize(16777215, 100))
        self.clear.setObjectName("clear")
        self.verticalLayout_2.addWidget(self.clear)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.input)
        self.gridLayout.addWidget(self.frame_container, 0, 1, 1, 1)
        self.bottom = QtWidgets.QFrame(self.centralwidget)
        self.bottom.setMaximumSize(QtCore.QSize(16777215, 10))
        self.bottom.setStyleSheet("QFrame {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom.setObjectName("bottom")
        self.gridLayout.addWidget(self.bottom, 1, 0, 1, 2)
        self.frame_menu = QtWidgets.QFrame(self.centralwidget)
        self.frame_menu.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_menu.setStyleSheet("QFrame {\n"
"    background-color: rgb(222, 222, 222);\n"
"}")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.sourceName = QtWidgets.QLabel(self.frame_menu)
        self.sourceName.setGeometry(QtCore.QRect(0, 0, 250, 621))
        self.sourceName.setMinimumSize(QtCore.QSize(250, 0))
        self.sourceName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.sourceName.setWordWrap(True)
        self.sourceName.setObjectName("sourceName")
        self.label = QtWidgets.QLabel(self.frame_menu)
        self.label.setGeometry(QtCore.QRect(0, 630, 251, 16))
        self.label.setStyleSheet("QLabel {\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.label.setObjectName("label")
        self.sourceId = QtWidgets.QLineEdit(self.frame_menu)
        self.sourceId.setGeometry(QtCore.QRect(0, 650, 251, 31))
        self.sourceId.setObjectName("sourceId")
        self.gridLayout.addWidget(self.frame_menu, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 853, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.chat.setText(_translate("MainWindow", "TextLabel"))
        self.post.setText(_translate("MainWindow", "发送"))
        self.clear.setText(_translate("MainWindow", "清空"))
        self.sourceName.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "请选择sourceId"))
